import * as Sharing from 'expo-sharing';
import * as FileSystem from 'expo-file-system';
import i18n from '../i18n';
import apiClient from './apiService';

const getSafeDate = (value) => {
  const date = value instanceof Date ? value : new Date(value);
  if (Number.isNaN(date.getTime())) {
    return new Date();
  }
  return date;
};

const formatDateKey = (value) => {
  const date = getSafeDate(value);
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
};

const escapeHtml = (value = '') => String(value)
  .replace(/&/g, '&amp;')
  .replace(/</g, '&lt;')
  .replace(/>/g, '&gt;')
  .replace(/"/g, '&quot;')
  .replace(/'/g, '&#039;');

export const fetchDailyMentalReport = async (userId, language = i18n.language || 'en') => {
  try {
    const response = await apiClient.post('/reports/daily', {
      userId,
      language,
      includePersistence: true,
    });

    if (response.status === 200) {
      return {
        success: true,
        report: {
          ...(response.data || {}),
          language,
        },
      };
    }

    throw new Error('Invalid daily report response');
  } catch (error) {
    console.warn('[ReportService] Daily report fetch failed:', error.message || error);
    return {
      success: false,
      report: null,
      error: error.response?.data?.error || 'Failed to generate daily report',
    };
  }
};

export const buildDailyReportHtml = ({ report, userName = 'MindCare User' } = {}) => {
  const reportDate = formatDateKey(report?.date || new Date());
  const moodRecoveryLine = report?.moodRecovery
    ? `${escapeHtml(report.moodRecovery.initialMood)} -> ${escapeHtml(report.moodRecovery.finalMood)} (Score: ${report.moodRecovery.recoveryScore > 0 ? `+${report.moodRecovery.recoveryScore}` : report.moodRecovery.recoveryScore})`
    : 'No mood recovery data available for today.';

  const summary = escapeHtml(report?.summary || 'No summary available.');

  return `
  <html>
    <head>
      <meta charset="utf-8" />
      <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; padding: 28px; color: #16364F; }
        .title { font-size: 26px; font-weight: 700; margin-bottom: 6px; }
        .date { font-size: 13px; color: #5A7A92; margin-bottom: 24px; }
        .section { margin-bottom: 18px; }
        .section h2 { font-size: 16px; margin-bottom: 8px; color: #204F73; }
        .card { background: #F2F8FD; border: 1px solid #DCEBF7; border-radius: 12px; padding: 14px; line-height: 1.5; }
        .muted { color: #5A7A92; font-size: 12px; }
      </style>
    </head>
    <body>
      <div class="title">Daily Mental Health Report</div>
      <div class="date">Date: ${escapeHtml(reportDate)} | User: ${escapeHtml(userName)}</div>

      <div class="section">
        <h2>Mood Summary</h2>
        <div class="card">${summary}</div>
      </div>

      <div class="section">
        <h2>AI-Generated Insights</h2>
        <div class="card">
          Chats in last 24h: ${Number(report?.insights?.chatCountLast24Hours || 0)}<br/>
          Mood check-ins in last 24h: ${Number(report?.insights?.moodCountLast24Hours || 0)}
        </div>
      </div>

      <div class="section">
        <h2>Mood Recovery Score</h2>
        <div class="card">${escapeHtml(moodRecoveryLine)}</div>
      </div>

      <div class="muted">Generated by MindCare AI assistant</div>
    </body>
  </html>
  `;
};

export const generateDailyReportPdf = async ({ report, userName = 'MindCare User' } = {}) => {
  const buildLocalPdfFallback = async () => {
    const Print = await import('expo-print');
    const html = buildDailyReportHtml({ report, userName });
    const printable = await Print.printToFileAsync({ html, base64: false });

    const datePart = formatDateKey(report?.date || new Date());
    const fileName = `mental_report_${datePart}.pdf`;
    const destinationUri = `${FileSystem.documentDirectory || ''}${fileName}`;

    let savedUri = printable?.uri || destinationUri;
    if (FileSystem.documentDirectory) {
      try {
        await FileSystem.copyAsync({
          from: printable.uri,
          to: destinationUri,
        });
        savedUri = destinationUri;
      } catch (_copyError) {
        savedUri = printable.uri;
      }
    }

    return {
      uri: savedUri,
      fileName,
    };
  };

  const datePart = formatDateKey(report?.date || new Date());
  const fileName = `mental_report_${datePart}.pdf`;
  const destinationUri = `${FileSystem.documentDirectory || ''}${fileName}`;

  const userId = report?.userId;
  if (!userId) {
    throw new Error('Missing userId for PDF export');
  }

  const pdfUrl = apiClient.getUri({
    url: '/reports/daily/pdf',
    params: {
      userId,
      language: report?.language || i18n.language || 'en',
    },
  });

  let savedUri = destinationUri;
  try {
    const downloadResult = await FileSystem.downloadAsync(pdfUrl, destinationUri);

    if (!downloadResult || Number(downloadResult.status) !== 200) {
      throw new Error(`Backend PDF endpoint returned status ${downloadResult?.status || 'unknown'}`);
    }

    savedUri = downloadResult?.uri || destinationUri;
  } catch (downloadError) {
    console.warn('[ReportService] Backend PDF download failed, falling back to local PDF:', downloadError?.message || downloadError);
    try {
      const fallback = await buildLocalPdfFallback();
      savedUri = fallback.uri;
    } catch (fallbackError) {
      console.warn('[ReportService] Local PDF fallback failed:', fallbackError?.message || fallbackError);
      throw new Error('PDF export failed on both backend and device. Restart Expo and backend, then try again.');
    }
  }

  const canShare = await Sharing.isAvailableAsync();
  if (canShare) {
    try {
      await Sharing.shareAsync(savedUri, {
        mimeType: 'application/pdf',
        dialogTitle: fileName,
        UTI: 'com.adobe.pdf',
      });
    } catch (shareError) {
      console.warn('[ReportService] PDF share failed:', shareError?.message || shareError);
    }
  }

  return {
    uri: savedUri,
    fileName,
  };
};
