import React, { useState } from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity, ActivityIndicator, Alert, Platform, Share } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import Animated, { FadeInDown } from 'react-native-reanimated';
import * as FileSystem from 'expo-file-system/legacy';
import * as Sharing from 'expo-sharing';
import TopBackButton from '../components/ui/Premium/TopBackButton';
import { getFirebaseInstance, getAuth_ } from '../firebase';

// Light color scheme
const COLORS = {
  background: '#F0F4F8',
  card: '#FFFFFF',
  primary: '#4A90D9',
  success: '#2ECC71',
  warning: '#F39C12',
  danger: '#E74C3C',
  text: '#2C3E50',
  textLight: '#7F8C8D',
  border: '#E8EDF2',
  shadow: 'rgba(0,0,0,0.06)',
  gold: '#F1C40F',
  purple: '#8E44AD',
  accent: '#E67E22',
};

export default function ReportScreen() {
  const [loading, setLoading] = useState(false);
  const [downloading, setDownloading] = useState(false);
  const [reportType, setReportType] = useState('Daily');
  const [reportData, setReportData] = useState(null);

  const generateReport = async () => {
    setLoading(true);
    try {
      const currentUser = getAuth_()?.currentUser;
      if (!currentUser) return;
      
      await new Promise(resolve => setTimeout(resolve, 1500));
      
      Alert.alert(
        "✨ XP Earned!",
        `You earned 15 XP for generating a report.`
      );

      setReportData({
        type: reportType,
        score: Math.floor(Math.random() * 20) + 80,
        moodSummary: `Your mood has been predominantly calm and balanced over this ${reportType.toLowerCase()} period.`,
        activitySummary: `You completed ${Math.floor(Math.random() * 10) + 5} activities, focusing highly on mindfulness.`,
        achievements: Math.floor(Math.random() * 3),
        recommendation: "Try adding a 5-minute morning meditation to boost your energy levels further."
      });

    } catch (error) {
      console.warn("Error generating report:", error);
      Alert.alert('Error', 'Failed to generate report. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const generateReportContent = () => {
    if (!reportData) return '';
    
    const date = new Date().toLocaleDateString('en-US', { 
      weekday: 'long', 
      month: 'long', 
      day: 'numeric',
      year: 'numeric'
    });
    
    return `
╔══════════════════════════════════════════════════════════════╗
║                    WELLNESS REPORT                          ║
╚══════════════════════════════════════════════════════════════╝

📋 ${reportData.type} Report
📅 Generated: ${date}

───────────────────────────────────────────────────────────────

📊 OVERALL SCORE
Score: ${reportData.score}%

───────────────────────────────────────────────────────────────

😊 MOOD ANALYSIS
${reportData.moodSummary}

───────────────────────────────────────────────────────────────

⚡ ACTIVITY OVERVIEW
${reportData.activitySummary}

───────────────────────────────────────────────────────────────

🏆 ACHIEVEMENTS
${reportData.achievements} achievement${reportData.achievements !== 1 ? 's' : ''} unlocked during this period.

───────────────────────────────────────────────────────────────

💡 RECOMMENDATION
${reportData.recommendation}

───────────────────────────────────────────────────────────────

Generated by MindCare Wellness App
${new Date().getFullYear()} © MindCare
`;
  };

  const downloadReport = async () => {
    if (!reportData) {
      Alert.alert('No Report', 'Please generate a report first.');
      return;
    }

    setDownloading(true);
    try {
      const content = generateReportContent();
      const fileName = `Wellness_Report_${reportType}_${new Date().toISOString().split('T')[0]}.txt`;
      const filePath = FileSystem.documentDirectory + fileName;
      
      // Use the legacy API
      await FileSystem.writeAsStringAsync(filePath, content);
      
      // Check if file exists
      const fileInfo = await FileSystem.getInfoAsync(filePath);
      if (!fileInfo.exists) {
        throw new Error('File was not created successfully');
      }

      // Check if sharing is available
      const isSharingAvailable = await Sharing.isAvailableAsync();
      
      if (isSharingAvailable) {
        await Sharing.shareAsync(filePath, {
          mimeType: 'text/plain',
          dialogTitle: `Share ${reportType} Report`,
          UTI: 'public.plain-text',
        });
      } else {
        Alert.alert(
          'File Saved',
          `Report saved to your device.`,
          [{ text: 'OK' }]
        );
      }

      Alert.alert(
        "📄 Report Downloaded!",
        "You earned 10 XP for downloading your report."
      );

    } catch (error) {
      console.error('Error downloading report:', error);
      Alert.alert('Error', 'Failed to download report. Please try again.');
    } finally {
      setDownloading(false);
    }
  };

  const shareReport = async () => {
    if (!reportData) {
      Alert.alert('No Report', 'Please generate a report first.');
      return;
    }

    try {
      const content = generateReportContent();
      
      await Share.share({
        message: content,
        title: `${reportType} Wellness Report`,
      });
      
      Alert.alert(
        "📤 Report Shared!",
        "You earned 5 XP for sharing your report."
      );
    } catch (error) {
      console.error('Error sharing report:', error);
      Alert.alert('Error', 'Failed to share report. Please try again.');
    }
  };

  const getScoreColor = (score) => {
    if (score >= 80) return COLORS.success;
    if (score >= 60) return COLORS.warning;
    return COLORS.danger;
  };

  const getScoreEmoji = (score) => {
    if (score >= 80) return '😊';
    if (score >= 60) return '😐';
    return '😢';
  };

  return (
    <View style={[styles.container, { backgroundColor: COLORS.background }]}>
      <SafeAreaView style={{ flex: 1 }}>
        <TopBackButton fallbackRoute="WellnessDashboard" />
        
        <ScrollView 
          contentContainerStyle={styles.scrollContent}
          showsVerticalScrollIndicator={false}
        >
          {/* Header */}
          <Animated.View entering={FadeInDown.duration(600)}>
            <View style={styles.header}>
              <View>
                <Text style={{height:30}}></Text>
                <Text style={styles.title}>📊 Wellness Reports</Text>
                <Text style={styles.subtitle}>Deep insights into your journey</Text>
              </View>
            </View>
          </Animated.View>

          {/* Tabs */}
          <Animated.View entering={FadeInDown.delay(100).duration(600)} style={styles.tabsContainer}>
            {['Daily', 'Weekly', 'Monthly'].map((type) => (
              <TouchableOpacity 
                key={type} 
                style={[styles.tabButton, reportType === type && styles.tabButtonActive]}
                onPress={() => { setReportType(type); setReportData(null); }}
              >
                <Text style={[styles.tabText, reportType === type && styles.tabTextActive]}>
                  {type}
                </Text>
              </TouchableOpacity>
            ))}
          </Animated.View>

          {!reportData ? (
            <Animated.View entering={FadeInDown.delay(200).duration(600)}>
              <View style={styles.generateCard}>
                <View style={styles.generateIconWrap}>
                  <MaterialCommunityIcons name="file-document-outline" size={48} color={COLORS.primary} />
                </View>
                <Text style={styles.generateTitle}>Generate {reportType} Report</Text>
                <Text style={styles.generateSubtitle}>
                  Compile all your recent wellness data into a comprehensive summary.
                </Text>
                
                <TouchableOpacity 
                  style={[styles.generateBtn, loading && styles.generateBtnDisabled]} 
                  onPress={generateReport}
                  disabled={loading}
                  activeOpacity={0.8}
                >
                  {loading ? (
                    <ActivityIndicator color="#FFFFFF" size="small" />
                  ) : (
                    <>
                      <MaterialCommunityIcons name="creation" size={20} color="#FFFFFF" />
                      <Text style={styles.generateBtnText}>Generate Now</Text>
                    </>
                  )}
                </TouchableOpacity>
              </View>
            </Animated.View>
          ) : (
            <Animated.View entering={FadeInDown.duration(600)}>
              <View style={styles.reportCard}>
                {/* Report Header */}
                <View style={styles.reportHeader}>
                  <View>
                    <Text style={styles.reportTitle}>{reportData.type} Summary</Text>
                    <Text style={styles.reportDate}>
                      {new Date().toLocaleDateString('en-US', { 
                        weekday: 'long', 
                        month: 'long', 
                        day: 'numeric' 
                      })}
                    </Text>
                  </View>
                  <View style={[styles.scoreBadge, { backgroundColor: `${getScoreColor(reportData.score)}15` }]}>
                    <Text style={[styles.scoreEmoji, { color: getScoreColor(reportData.score) }]}>
                      {getScoreEmoji(reportData.score)}
                    </Text>
                    <Text style={[styles.scoreText, { color: getScoreColor(reportData.score) }]}>
                      {reportData.score}%
                    </Text>
                  </View>
                </View>

                {/* Mood Analysis */}
                <View style={styles.reportSection}>
                  <View style={styles.sectionHeader}>
                    <View style={[styles.sectionIcon, { backgroundColor: `${COLORS.primary}15` }]}>
                      <MaterialCommunityIcons name="emoticon-happy-outline" size={20} color={COLORS.primary} />
                    </View>
                    <Text style={styles.sectionTitle}>Mood Analysis</Text>
                  </View>
                  <Text style={styles.sectionText}>{reportData.moodSummary}</Text>
                </View>

                {/* Activity Overview */}
                <View style={styles.reportSection}>
                  <View style={styles.sectionHeader}>
                    <View style={[styles.sectionIcon, { backgroundColor: `${COLORS.success}15` }]}>
                      <MaterialCommunityIcons name="lightning-bolt-outline" size={20} color={COLORS.success} />
                    </View>
                    <Text style={styles.sectionTitle}>Activity Overview</Text>
                  </View>
                  <Text style={styles.sectionText}>{reportData.activitySummary}</Text>
                </View>

                {/* Achievements */}
                <View style={styles.reportSection}>
                  <View style={styles.sectionHeader}>
                    <View style={[styles.sectionIcon, { backgroundColor: `${COLORS.gold}15` }]}>
                      <MaterialCommunityIcons name="trophy-outline" size={20} color={COLORS.gold} />
                    </View>
                    <Text style={styles.sectionTitle}>Achievements</Text>
                  </View>
                  <Text style={styles.sectionText}>
                    You unlocked {reportData.achievements} achievement{reportData.achievements !== 1 ? 's' : ''} during this period.
                  </Text>
                </View>

                {/* Recommendation */}
                <View style={[styles.reportSection, styles.recommendationSection]}>
                  <View style={styles.sectionHeader}>
                    <View style={[styles.sectionIcon, { backgroundColor: `${COLORS.accent}15` }]}>
                      <MaterialCommunityIcons name="lightbulb-on-outline" size={20} color={COLORS.accent} />
                    </View>
                    <Text style={[styles.sectionTitle, { color: COLORS.accent }]}>Recommendation</Text>
                  </View>
                  <Text style={[styles.sectionText, { color: COLORS.text }]}>
                    {reportData.recommendation}
                  </Text>
                </View>

                {/* Action Buttons */}
                <View style={styles.actionButtons}>
                  <TouchableOpacity 
                    style={[styles.downloadBtn, downloading && styles.downloadBtnDisabled]}
                    onPress={downloadReport}
                    disabled={downloading}
                    activeOpacity={0.8}
                  >
                    {downloading ? (
                      <ActivityIndicator color="#FFFFFF" size="small" />
                    ) : (
                      <>
                        <MaterialCommunityIcons name="download" size={20} color="#FFFFFF" />
                        <Text style={styles.downloadBtnText}>Download</Text>
                      </>
                    )}
                  </TouchableOpacity>

                  <TouchableOpacity 
                    style={styles.shareBtn}
                    onPress={shareReport}
                    activeOpacity={0.8}
                  >
                    <MaterialCommunityIcons name="share-variant" size={20} color={COLORS.primary} />
                    <Text style={styles.shareBtnText}>Share</Text>
                  </TouchableOpacity>

                  <TouchableOpacity 
                    style={styles.newReportBtn}
                    onPress={() => setReportData(null)}
                    activeOpacity={0.8}
                  >
                    <MaterialCommunityIcons name="refresh" size={18} color={COLORS.primary} />
                    <Text style={styles.newReportBtnText}>New</Text>
                  </TouchableOpacity>
                </View>
              </View>
            </Animated.View>
          )}

          <View style={{ height: 40 }} />
        </ScrollView>
      </SafeAreaView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 40,
  },
  header: {
    marginBottom: 20,
  },
  title: {
    fontSize: 24,
    fontWeight: '700',
    color: COLORS.text,
  },
  subtitle: {
    fontSize: 14,
    color: COLORS.textLight,
    marginTop: 2,
  },
  tabsContainer: {
    flexDirection: 'row',
    backgroundColor: COLORS.card,
    borderRadius: 30,
    padding: 4,
    marginBottom: 20,
    shadowColor: COLORS.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  tabButton: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
    borderRadius: 26,
  },
  tabButtonActive: {
    backgroundColor: COLORS.primary,
  },
  tabText: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.textLight,
  },
  tabTextActive: {
    color: '#FFFFFF',
  },
  generateCard: {
    backgroundColor: COLORS.card,
    borderRadius: 20,
    padding: 32,
    alignItems: 'center',
    shadowColor: COLORS.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  generateIconWrap: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: `${COLORS.primary}10`,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  generateTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: COLORS.text,
    marginBottom: 8,
  },
  generateSubtitle: {
    fontSize: 14,
    color: COLORS.textLight,
    textAlign: 'center',
    marginBottom: 24,
    lineHeight: 20,
  },
  generateBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: COLORS.primary,
    paddingHorizontal: 28,
    paddingVertical: 14,
    borderRadius: 30,
  },
  generateBtnDisabled: {
    opacity: 0.7,
  },
  generateBtnText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  reportCard: {
    backgroundColor: COLORS.card,
    borderRadius: 20,
    padding: 20,
    shadowColor: COLORS.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  reportHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    marginBottom: 16,
  },
  reportTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: COLORS.text,
  },
  reportDate: {
    fontSize: 12,
    color: COLORS.textLight,
    marginTop: 2,
  },
  scoreBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    gap: 4,
  },
  scoreEmoji: {
    fontSize: 16,
  },
  scoreText: {
    fontSize: 16,
    fontWeight: '700',
  },
  reportSection: {
    marginBottom: 16,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 8,
  },
  sectionIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.text,
  },
  sectionText: {
    fontSize: 14,
    color: COLORS.textLight,
    lineHeight: 22,
    marginLeft: 42,
  },
  recommendationSection: {
    backgroundColor: `${COLORS.accent}08`,
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: `${COLORS.accent}15`,
    marginTop: 4,
  },
  actionButtons: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
  },
  downloadBtn: {
    flex: 0.35,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: COLORS.primary,
    paddingVertical: 12,
    borderRadius: 30,
  },
  downloadBtnDisabled: {
    opacity: 0.7,
  },
  downloadBtnText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  shareBtn: {
    flex: 0.35,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: `${COLORS.primary}10`,
    paddingVertical: 12,
    borderRadius: 30,
  },
  shareBtnText: {
    fontSize: 14,
    fontWeight: '500',
    color: COLORS.primary,
  },
  newReportBtn: {
    flex: 0.3,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    backgroundColor: `${COLORS.textLight}10`,
    paddingVertical: 12,
    borderRadius: 30,
  },
  newReportBtnText: {
    fontSize: 13,
    fontWeight: '500',
    color: COLORS.textLight,
  },
});